name: CI
on:
  push:
    paths-ignore:
      - "README.md"
      - "**/docs/**"
      - ".github/workflows/docs.yml"

  pull_request:
    branches:
      - master
      - dev

  schedule:
    - cron: "0 11 * * *"

jobs:
  publish-pypi:
    name: Publish to PyPi
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && (! endsWith(github.ref, 'dev'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
        - name: Build package
          run: |
            pip install wheel
            python setup.py sdist
        - name: Publish
          uses: pypa/gh-action-pypi-publish@v1.1.0
          with:
            user: __token__
            password: ${{ secrets.PYSPI_GITHUB_PYPI }}
            skip-existing: true

  test-publish-pypi:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install twine
        run: |
          python -m pip install twine
      - name: Build package
        run: |
          python setup.py sdist
      - name: List result
        run: |
          ls -lh dist
      - name: Check long_description
        run: |
          python -m twine check dist/*
