name: Docs
on: [push, release]

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache data folder
        uses: actions/cache@v2
        id: cache-data-folder
        with:
          path: ~/data
          key: data

      - name: Download data folder
        env:
          CACHE_HIT: ${{steps.cache-data-folder.outputs.cache-hit}}
        run: |
          echo "Getting data folder"
          if [[ "$CACHE_HIT" == 'true' ]]; then

          echo "data folder already in cache. using this."

          else
          echo "Download zip data folder."
          wget https://grb.mpe.mpg.de/pyspi_datafolder
          mv pyspi_datafolder ~/data.zip
          unzip -o ~/data.zip -d ~/
          fi

      - name: Set environment variables
        run: |
          mkdir /home/runner/PySPI_data
          export PYSPI=/home/runner/PySPI_data

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install black
          pip install --upgrade numpy ipython jupyter matplotlib
          pip install jupytext jupyterthemes
          pip install -r requirements.txt
          python setup.py develop

      - name: Copy data folder
        run: |
          rm -r pyspi/data
          cp -r ~/data pyspi/
          ls pyspi/data

      - name: Execute the notebooks
        shell: bash -l {0}
        env:
          PYSPI: /home/runner/PySPI_data
        run: |
          ls ~/
          ls pyspi
          ls pyspi/utils
          ls pyspi/utils/response
          ls docs/notebooks
          mkdir /home/runner/PySPI_data
          mkdir docs/md_docs/chains
          jupytext --to ipynb --execute docs/md_docs/*.md
          rm -r docs/md_docs/chains
          mv docs/md_docs/*.ipynb docs/notebooks/
          ls docs/notebooks

      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: pyspi/docs/notebooks

      - name: Sleep for 1 minutes
        uses: jakejarvis/wait-action@master
        with:
          time: '1m'

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
